---
- name: Start a containerized application in Docker
  hosts:
    - localhost
  gather_facts: true
  # necessary to execute docker commands
  become: true

  vars:
    docker_compose_dest: /opt/src_docker

  tasks:
    - name: Install docker
      apt:
        name: docker.io

    - name: Install docker-compose (1/2)
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: Install docker-compose (2/2)
      pip: 
        name: docker-compose
        executable: pip3

    - name: Run docker-compose if a repository is provided
      when: docker_compose_repo != "empty"
      block:
        - name: Checkout repository of docker-compose resources
          ansible.builtin.git:
            repo: "{{ docker_compose_repo }}"
            dest: "{{ docker_compose_dest }}"
            version: "{{ docker_compose_repo_branch }}"
        # TODO: add check for existance of docker-compose.[yml|yaml]?
        - name: Create and start services
          community.docker.docker_compose:
            project_src: "{{ docker_compose_dest }}/{{ docker_compose_directory }}"

