---
- name: Start a containerized application in Docker
  hosts:
    - localhost
  gather_facts: true
  # necessary to execute docker commands
  become: true

  vars:
    dockerfile_dest: /opt/src_docker

  tasks:
    - name: Install docker
      apt:
        name: docker.io

    - name: Build and run container from Dockerfile
      when: dockerfile_url != "empty"
      block:
        # We set the default URL to the Dockerfile to "empty" of the 
        # `dockerfile_url` parameter
        - name: Download Dockerfile
          get_url:
            url: "{{ dockerfile_url }}"
            dest: "{{ dockerfile_dest }}/Dockerfile"
        - name: Check that the Dockerfile exists
          stat:
            path: "{{ dockerfile_dest }}/Dockerfile"
          register: stat_result_dockerfile
        - name: Build Docker image
          community.docker.docker_image:
            build:
              path: "{{ dockerfile_dest }}"
            name: src_image
            source: build
          when: stat_result_dockerfile.stat.exists
        - name: Run container with built image
          community.docker.docker_container:
            name: src_container
            image: src_image
            command: "{{ docker_command }}"
            # `detach` and `tty` keep the docker container running in background
            detach: yes
            tty: yes

    - name: Pull and run container from specified image
      when: dockerfile_url == "empty"
      community.docker.docker_container:
        name: src_container
        image: "{{ docker_image }}"
        command: "{{ docker_command }}"
        # `detach` and `tty` keep the docker container running in background
        detach: yes
        tty: yes
