---
- name: Start a containerized application in Docker
  hosts:
    - localhost
  gather_facts: true
  # necessary to execute docker commands
  become: true

  tasks:
    - name: Install docker
      apt:
        name: docker.io
    - name: Start the requested Docker container
      community.docker.docker_container:
        name: "{{ docker-container-name }}"
        image: "{{ docker-image }}"
        # `detach` and `tty` keep the docker container running in background
        detach: yes
        tty: yes
