---
- name: Start a containerized application in Docker
  hosts:
    - localhost
  gather_facts: true

  tasks:
    - name: Start the requested Docker container
      community.docker.docker_container:
        name: "{{ docker-container-name }}"
        image: "{{ docker-image }}"
        command: "{{ docker-command }}"
