---
- name: Installs BioDynaMo from source (master)
  hosts:
    - localhost
  gather_facts: true

  tasks:
    - name: Install BioDynaMo from source
      block:
        - name: Install prerequisites
          apt:
            name:
              - sudo
              - curl
              - git
        - name: Execute the installer
          environment:
            SILENT_INSTALL: 1
            BDM_CMAKE_FLAGS: "CMAKE_INSTALL_PREFIX=/opt/biodynamo"
            BDM_INSTALL: master
          shell: curl https://biodynamo.org/install | bash
