---
- name: Configure node for access to the EESSI stack
  hosts:
    - localhost
  gather_facts: true

  tasks:
    - name: Ubuntu installation of EESSI client
      when: ansible_distribution == 'Ubuntu'
      block:
        - name: Install prerequisites
          apt:
            name:
              - sudo
              - wget
        - name: Download EESSI installation
          get_url:
            url: https://raw.githubusercontent.com/EESSI/eessi-demo/main/scripts/install_cvmfs_x86_64_Ubuntu.sh
            dest: /tmp/install_cvmfs_x86_64_Ubuntu.sh
            mode: 0755
        - name: Execute the zsh-installer.sh
          shell: /tmp/install_cvmfs_x86_64_Ubuntu.sh

    - name: CentOS installation of EESSI client
      when: ansible_distribution == 'CentOS'
      block:
        - name: Install prerequisites
          yum:
            name: sudo
        - name: Download EESSI installation
          get_url:
            url: https://raw.githubusercontent.com/EESSI/eessi-demo/main/scripts/install_cvmfs_aarch64_RHEL7.sh
            dest: /tmp/install_cvmfs_aarch64_RHEL7.sh
            mode: 0755
        - name: Install and configure EESSI
          shell: /tmp/install_cvmfs_aarch64_RHEL7.sh
        - shell: ls /cvmfs/pilot.eessi-hpc.org/2021.06/init/bash
